
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported fields

This document describes the fields that are exported by the
nginxbeat. They are grouped in the
following categories:

* <<exported-fields-env>>
* <<exported-fields-nginx>>

[[exported-fields-env]]
=== Common fields fields

Contains common fields available in all event types.



==== timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the measurements were taken. The precision is in milliseconds. The timezone is UTC.


==== type

required: True

Set to "nginx" to specify that are Nginx status.


==== count

type: int

required: True

For how many transactions is this event representative. This is generally the inverse of the sampling rate. For example, for a sample rate of 1/10, the count is 10. The count is used by the UIs to return estimated values. Reserved for future usage.


==== shipper

type: string

Name of the shipper sending the statistics


[[exported-fields-nginx]]
=== Nginx status fields

Contains Nginx status. Details that you can get by reading the Nginx Plus status page.



==== version

type: int

Version of the Nginx Plus status data set.


==== nginx_version

type: int

Version of Nginx.


==== address

type: string

The address of the server that accepted status request.


==== generation

type: int

The total number of configuration reloads.


==== load_timestamp

type: int

Time of the last reload of configuration, in milliseconds since Epoch.


==== timestamp

type: int

Current time in milliseconds since Epoch.


==== pid

type: int

The ID of the worker process that handled status request.


=== processes fields


==== respawned

type: int

The total number of abnormally terminated and respawned child processes.


=== connections fields


==== accepted

type: int

The total number of accepted client connections.


==== dropped

type: int

The total number of dropped client connections.


==== active

type: int

The current number of active client connections.


==== idle

type: int

The current number of idle client connections.


=== ssl fields


==== handshakes

type: int

The total number of successful SSL handshakes.


==== handshakes_failed

type: int

The total number of failed SSL handshakes.


==== session_reuses

type: int

The total number of session reuses during SSL handshake.


=== requests fields


==== total

type: int

The total number of client requests.


==== current

type: int

The current number of client requests.


==== server_zones

type: nested

==== upstreams

type: nested

==== caches

type: nested

==== stream

type: nested

