
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported fields

This document describes the fields that are exported by the
nginxbeat. They are grouped in the
following categories:

* <<exported-fields-env>>
* <<exported-fields-nginx>>

[[exported-fields-env]]
=== Common fields fields

Contains common fields available in all event types.



==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the measurements were taken. The precision is in milliseconds. The timezone is UTC.


==== type

required: True

Set to "nginx" to specify that are Nginx status.


==== count

type: int

required: True

For how many transactions is this event representative. This is generally the inverse of the sampling rate. For example, for a sample rate of 1/10, the count is 10. The count is used by the UIs to return estimated values. Reserved for future usage.


==== shipper

type: string

Name of the shipper sending the statistics


[[exported-fields-nginx]]
=== Nginx status fields

Contains Nginx status. Details that you can get by reading the Nginx stub status page.



==== active

type: int

The current number of active client connections including Waiting connections.


==== accepts

type: int

The total number of accepted client connections.


==== handled

type: int

The total number of handled client connections.


==== dropped

type: int

The total number of dropped client connections.


==== requests

type: int

The total number of client requests.


==== current

type: int

The current number of client requests.


==== reading

type: int

The current number of connections where nginx is reading the request header.


==== writing

type: int

The current number of connections where nginx is writing the response back to the client.


==== waiting

type: int

The current number of idle client connections waiting for a request.


