
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported fields

This document describes the fields that are exported by the
nginxbeat. They are grouped in the
following categories:

* <<exported-fields-env>>
* <<exported-fields-stub>>
* <<exported-fields-plus>>
* <<exported-fields-zone>>
* <<exported-fields-upstream>>
* <<exported-fields-cache>>
* <<exported-fields-tcpzone>>
* <<exported-fields-tcpupstream>>

[[exported-fields-env]]
=== Common fields fields

Contains common fields available in all event types.



==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the measurements were taken. The precision is in milliseconds. The timezone is UTC.


==== type

required: True

Set to "stub" to specify that are Nginx stub status. Set to "plus" to specify that are Nginx Plus status. Set to "zone" to specify that are Nginx server zone status. Set to "upstream" to specify that are Nginx upstream group status. Set to "cache" to specify that are Nginx cache zone status. Set to "tcpupstream" to specify that are Nginx TCP upstream status. Set to "tcpzone" to specify that are Nginx TCP zone status.


==== count

type: int

required: True

For how many transactions is this event representative. This is generally the inverse of the sampling rate. For example, for a sample rate of 1/10, the count is 10. The count is used by the UIs to return estimated values. Reserved for future usage.


==== shipper

type: string

Name of the shipper sending the statistics


==== source

type: string

Source of the data set.


[[exported-fields-stub]]
=== Nginx stub status fields

Contains Nginx stub status. Details that you can get by reading the Nginx stub status page.



==== active

type: int

The current number of active client connections including Waiting connections.


==== accepts

type: int

The total number of accepted client connections.


==== handled

type: int

The total number of handled client connections.


==== dropped

type: int

The total number of dropped client connections.


==== requests

type: int

The total number of client requests.


==== current

type: int

The current number of client requests.


==== reading

type: int

The current number of connections where nginx is reading the request header.


==== writing

type: int

The current number of connections where nginx is writing the response back to the client.


==== waiting

type: int

The current number of idle client connections waiting for a request.


[[exported-fields-plus]]
=== Nginx Plus status fields

Contains Nginx Plus status. Details that you can get by reading the Nginx Plus status page.



==== version

type: int

Version of the Nginx Plus status data set.


==== nginx_version

type: int

Version of Nginx.


==== address

type: string

The address of the server that accepted status request.


==== generation

type: int

The total number of configuration reloads.


==== load_timestamp

type: int

Time of the last reload of configuration, in milliseconds since Epoch.


==== timestamp

type: int

Current time in milliseconds since Epoch.


==== pid

type: int

The ID of the worker process that handled status request.


=== processes fields


==== respawned

type: int

The total number of abnormally terminated and respawned child processes.


=== connections fields


==== accepted

type: int

The total number of accepted client connections.


==== dropped

type: int

The total number of dropped client connections.


==== active

type: int

The current number of active client connections.


==== idle

type: int

The current number of idle client connections.


=== ssl fields


==== handshakes

type: int

The total number of successful SSL handshakes.


==== handshakes_failed

type: int

The total number of failed SSL handshakes.


==== session_reuses

type: int

The total number of session reuses during SSL handshake.


=== requests fields


==== total

type: int

The total number of client requests.


==== current

type: int

The current number of client requests.


[[exported-fields-zone]]
=== Nginx status zone status fields

Contains Nginx server zone status. Details that you can get by reading the Nginx Plus status page.



==== name

type: string

The name of the server zone.


==== version

type: int

Version of the Nginx Plus status data set.


==== nginx_version

type: int

Version of Nginx.


==== processing

type: int

The number of client requests that are currently being processed.


==== requests

type: int

The total number of client requests received from clients.


=== responses fields


==== total

type: int

The total number of responses sent to clients.


==== 1xx

type: int

The number of responses with status codes 1xx.


==== 2xx

type: int

The number of responses with status codes 2xx.


==== 3xx

type: int

The number of responses with status codes 3xx.


==== 4xx

type: int

The number of responses with status codes 4xx.


==== 5xx

type: int

The number of responses with status codes 5xx.


==== discarded

type: int

The total number of requests completed without sending a response.


==== received

type: int

The total number of bytes received from clients.


==== sent

type: int

The total number of bytes sent to clients.


[[exported-fields-upstream]]
=== Nginx upstream group status fields

Contains Nginx upstream group status. Details that you can get by reading the Nginx Plus status page.



==== name

type: string

The name of the upstream group.


==== version

type: int

Version of the Nginx Plus status data set.


==== nginx_version

type: int

Version of Nginx.


=== peers fields


==== id

type: int

The ID of the server.


==== server

type: string

An address of the server.


==== backup

type: boolean

A boolean value indicating whether the server is a backup server.


==== weight

type: int

Weight of the server.


==== state

type: string

Current state, which may be one of "up", "draining", "down", "unavail", or "unhealthy".


==== active

type: int

The current number of active connections.


==== max_conns

type: int

The max_conns limit for the server.


==== requests

type: int

The total number of client requests forwarded to this server.


=== responses fields


==== total

type: int

The total number of responses obtained from this server.


==== 1xx

type: int

The number of responses with status codes 1xx.


==== 2xx

type: int

The number of responses with status codes 2xx.


==== 3xx

type: int

The number of responses with status codes 3xx.


==== 4xx

type: int

The number of responses with status codes 4xx.


==== 5xx

type: int

The number of responses with status codes 5xx.


==== sent

type: int

The total number of bytes sent to this server.


==== received

type: int

The total number of bytes received from this server.


==== fails

type: int

The total number of unsuccessful attempts to communicate with the server.


==== unavail

type: int

How many times the server became unavailable for client requests (state "unavail") due to the number of unsuccessful attempts reaching the max_fails threshold.


=== health_checks fields


==== checks

type: int

The total number of health check requests made.


==== fails

type: int

The number of failed health checks.


==== unhealthy

type: int

How many times the server became unhealthy (state "unhealthy").


==== last_passed

type: int

Boolean indicating if the last health check request was successful and passed tests.


==== downtime

type: int

Total time the server was in the "unavail" and "unhealthy" states.


==== downstart

type: int

The time (in milliseconds since Epoch) when the server became "unavail" or "unhealthy".


==== selected

type: int

The time (in milliseconds since Epoch) when the server was last selected to process a request.


==== header_time

type: int

The average time to get the response header from the server.


==== response_time

type: int

The average time to get the full response from the server.


==== keepalive

type: int

The current number of idle keepalive connections.


=== queue fields


==== size

type: int

The current number of requests in the queue.


==== max_size

type: int

The maximum number of requests that can be in the queue at the same time.


==== overflows

type: int

The total number of requests rejected due to the queue overflow.


[[exported-fields-cache]]
=== Nginx cache zone status fields

Contains Nginx cache zone status. Details that you can get by reading the Nginx Plus status page.



==== name

type: string

The name of the cache zone.


==== version

type: int

Version of the Nginx Plus status data set.


==== nginx_version

type: int

Version of Nginx.


==== size

type: int

The current size of the cache.


==== max_size

type: int

The limit on the maximum size of the cache specified in the configuration.


==== cold

type: boolean

A boolean value indicating whether the "cache loader" process is still loading data from disk into the cache.


=== hit fields


==== responses

type: int

The total number of responses read from the cache hit.


==== bytes

type: int

The total number of bytes read from the cache.


=== stale fields


==== responses

type: int

The total number of responses read from the cache stale.


==== bytes

type: int

The total number of bytes read from the cache.


=== updating fields


==== responses

type: int

The total number of responses read from the updating cache.


==== bytes

type: int

The total number of bytes read from the cache.


=== revalidated fields


==== responses

type: int

The total number of responses read from the revalidated cache.


==== bytes

type: int

The total number of bytes read from the cache.


=== miss fields


==== responses

type: int

The total number of responses not taken from the cache misses.


==== bytes

type: int

The total number of bytes read from the proxied server.


==== responses_written

type: int

The total number of responses written to the cache.


==== bytes_written

type: int

The total number of bytes written to the cache.


[[exported-fields-tcpzone]]
=== Nginx TCP zone status fields

Contains Nginx TCP zone status. Details that you can get by reading the Nginx Plus status page.



==== name

type: string

The name of the TCP zone.


==== version

type: int

Version of the Nginx Plus status data set.


==== nginx_version

type: int

Version of Nginx.


==== processing

type: int

The number of client requests that are currently being processed.


==== connections

type: int

The total number of connections accepted from clients.


==== received

type: int

The total number of bytes received from clients.


==== sent

type: int

The total number of bytes sent to clients.


[[exported-fields-tcpupstream]]
=== Nginx TCP upstream status fields

Contains Nginx TCP upstream status. Details that you can get by reading the Nginx Plus status page.



==== name

type: string

The name of the TCP upstream group.


==== version

type: int

Version of the Nginx Plus status data set.


==== nginx_version

type: int

Version of Nginx.


=== peers fields


==== id

type: int

The ID of the server.


==== server

type: string

An address of the server.


==== backup

type: boolean

A boolean value indicating whether the server is a backup server.


==== weight

type: int

Weight of the server.


==== state

type: string

Current state, which may be one of "up", "draining", "down", "unavail", or "unhealthy".


==== active

type: int

The current number of active connections.


==== connections

type: int

The total number of client connections forwarded to this server.


==== connect_time

type: int

The average time to connect to the upstream server.


==== first_byte_time

type: int

The average time to receive the first byte of data.


==== response_time

type: int

The average time to receive the last byte of data.


==== sent

type: int

The total number of bytes sent to this server.


==== received

type: int

The total number of bytes received from this server.


==== fails

type: int

The total number of unsuccessful attempts to communicate with the server.


==== unavail

type: int

How many times the server became unavailable for client requests (state "unavail") due to the number of unsuccessful attempts reaching the max_fails threshold.


=== health_checks fields


==== checks

type: int

The total number of health check requests made.


==== fails

type: int

The number of failed health checks.


==== unhealthy

type: int

How many times the server became unhealthy (state "unhealthy").


==== last_passed

type: int

Boolean indicating if the last health check request was successful and passed tests.


==== downtime

type: int

Total time the server was in the "unavail" and "unhealthy" states.


==== downstart

type: int

The time (in milliseconds since Epoch) when the server became "unavail" or "unhealthy".


==== selected

type: int

The time (in milliseconds since Epoch) when the server was last selected to process a request.


